// This file is generated by Slice Machine. Update with care!

import AboutUs from './AboutUs';
import FormContact from './FormContact';
import Hero from './Hero';
import Logos from './Logos';
import Projects from './Projects';
import Team from './Team';
import WriteUsSnippet from './WriteUsSnippet';

export {
	AboutUs,
	FormContact,
	Hero,
	Logos,
	Projects,
	Team,
	WriteUsSnippet,
};

export const components = {
	about_us: AboutUs,
	form_contact: FormContact,
	hero: Hero,
	logos: Logos,
	projects: Projects,
	team: Team,
	write_us_snippet: WriteUsSnippet,
};
